export const INVALID_EMAIL = 'INVALID_EMAIL';
export const TOO_LONG_STRING = 'TOO_LONG_STRING';
export const TOO_SHORT_STRING = 'TOO_SHORT_STRING';
export const NOT_MATCHES_TO_PATTERN = 'NOT_MATCHES_TO_PATTERN';
